# -*- coding: utf-8 -*-
"""VoltAI v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14_tSFXGvRCNyhdbJZ09O8FElAwaY5CLl
"""

# @title **Step 1: Install & Import Required Libraries**
!pip install -q numpy pandas matplotlib scikit-learn xgboost seaborn tqdm

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import zipfile
import glob
import re
from tqdm import tqdm
import warnings
warnings.filterwarnings('ignore')

print("✅ Libraries imported successfully.")

# @title **Step 2: Upload and Extract Kaggle Zip File**
print("📤 Please upload the NASA Battery Dataset zip file...")

# Method 1: Using Google Colab file upload
from google.colab import files
import io

# Create upload button
uploaded = files.upload()

# Find the uploaded zip file
zip_filename = None
for filename in uploaded.keys():
    if filename.endswith('.zip'):
        zip_filename = filename
        print(f"✅ Found zip file: {filename} ({uploaded[filename].__sizeof__()/1024/1024:.1f} MB)")
        break

if zip_filename:
    # Extract the zip file
    extract_path = 'nasa_battery_data'

    with zipfile.ZipFile(io.BytesIO(uploaded[zip_filename]), 'r') as zip_ref:
        # Get list of files
        file_list = zip_ref.namelist()
        print(f"\n📁 Zip file contains {len(file_list)} files/folders")

        # Show first 10 items
        print("\n📋 First 10 items in zip:")
        for item in file_list[:10]:
            print(f"  • {item}")

        # Extract all files
        print(f"\n📂 Extracting to: {extract_path}")
        zip_ref.extractall(extract_path)

    print("✅ Extraction complete!")

    # Find the cleaned_dataset directory
    cleaned_path = None
    for root, dirs, files in os.walk(extract_path):
        if 'cleaned_dataset' in dirs:
            cleaned_path = os.path.join(root, 'cleaned_dataset')
            break
        elif 'data' in dirs and any(f.endswith('.csv') for f in files):
            cleaned_path = root
            break

    if cleaned_path:
        print(f"\n🔍 Found data at: {cleaned_path}")
        # List contents
        print("\n📋 Directory contents:")
        !find "{cleaned_path}" -type f -name "*.csv" | head -20
    else:
        print("\n❌ Could not find cleaned_dataset directory")
        # Try to find CSV files in any directory
        csv_files = glob.glob(f'{extract_path}/**/*.csv', recursive=True)
        if csv_files:
            print(f"\n✅ Found {len(csv_files)} CSV files in alternative location")
            cleaned_path = os.path.dirname(csv_files[0])
        else:
            print("\n❌ No CSV files found in extracted archive")
            cleaned_path = None
else:
    print("\n❌ No zip file uploaded. Creating synthetic data for demonstration...")
    cleaned_path = None

# @title **FIXED Step 3: Correct CSV Loading with Zero Division Fix**
print("📊 Loading your NASA battery dataset...")

def load_your_nasa_dataset_fixed(base_path, max_files=50):
    """
    Load CSV files with numeric names (00001.csv, 00002.csv, etc.)
    """
    all_data = []
    battery_stats = {}

    try:
        # Find all CSV files
        csv_files = glob.glob(os.path.join(base_path, "**/*.csv"), recursive=True)
        if not csv_files:
            csv_files = glob.glob(os.path.join(base_path, "*.csv"))

        print(f"Found {len(csv_files)} CSV files")

        if len(csv_files) == 0:
            print("❌ No CSV files found")
            return None

        # Sort files numerically (00001.csv, 00002.csv, etc.)
        def extract_number(filename):
            match = re.search(r'(\d+)\.csv$', filename)
            return int(match.group(1)) if match else 0

        csv_files = sorted(csv_files, key=extract_number)

        files_to_load = min(max_files, len(csv_files))
        print(f"Loading {files_to_load} CSV files in order...")

        # NASA battery IDs
        nasa_battery_ids = ['B0005', 'B0006', 'B0007', 'B0018']

        # Group into 4 batteries (standard NASA dataset)
        num_batteries = 4
        cycles_per_battery = max(1, files_to_load // num_batteries)  # Prevent division by zero

        print(f"\n📈 Creating {num_batteries} batteries from {files_to_load} cycles")
        print(f"   • Cycles per battery: ~{cycles_per_battery}")

        successful_loads = 0

        for file_idx, file_path in enumerate(tqdm(csv_files[:files_to_load], desc="Loading CSV files")):
            try:
                filename = os.path.basename(file_path)

                # Extract numeric part from filename (00001.csv -> 1)
                match = re.search(r'(\d+)\.csv$', filename)
                if match:
                    cycle_num = int(match.group(1))
                else:
                    cycle_num = file_idx + 1

                # Determine which battery this cycle belongs to
                battery_idx = min((cycle_num - 1) // cycles_per_battery, num_batteries - 1)
                battery_id = nasa_battery_ids[battery_idx]

                # Calculate cycle number within this battery (1-based)
                cycle_in_battery = (cycle_num - 1) % cycles_per_battery + 1

                # Load CSV file
                df_cycle = pd.read_csv(file_path)

                # Standardize column names (case-insensitive)
                column_mapping = {}
                for col in df_cycle.columns:
                    col_lower = str(col).strip().lower()

                    if 'voltage' in col_lower and 'load' not in col_lower:
                        column_mapping[col] = 'voltage_measured'
                    elif 'current' in col_lower and 'load' not in col_lower:
                        column_mapping[col] = 'current_measured'
                    elif 'temperature' in col_lower:
                        column_mapping[col] = 'temperature_measured'
                    elif 'current' in col_lower and 'load' in col_lower:
                        column_mapping[col] = 'current_load'
                    elif 'voltage' in col_lower and 'load' in col_lower:
                        column_mapping[col] = 'voltage_load'
                    elif 'time' in col_lower:
                        column_mapping[col] = 'time'
                    elif col_lower in ['volt', 'v']:
                        column_mapping[col] = 'voltage_measured'
                    elif col_lower in ['curr', 'i', 'amp']:
                        column_mapping[col] = 'current_measured'
                    elif col_lower in ['temp', 't']:
                        column_mapping[col] = 'temperature_measured'

                if column_mapping:
                    df_cycle = df_cycle.rename(columns=column_mapping)

                # Add missing columns if needed
                expected_cols = ['voltage_measured', 'current_measured', 'temperature_measured',
                               'current_load', 'voltage_load', 'time']

                for col in expected_cols:
                    if col not in df_cycle.columns:
                        df_cycle[col] = np.nan

                # Add metadata
                df_cycle['battery_id'] = battery_id
                df_cycle['cycle'] = cycle_in_battery
                df_cycle['filename'] = filename
                df_cycle['original_cycle_num'] = cycle_num
                df_cycle['file_index'] = file_idx + 1

                # Calculate simple capacity estimate
                if 'time' in df_cycle.columns and 'current_measured' in df_cycle.columns:
                    if len(df_cycle) > 1 and not df_cycle['time'].isna().all():
                        try:
                            time_values = df_cycle['time'].values
                            current_values = df_cycle['current_measured'].values

                            # Remove NaN values
                            mask = ~(np.isnan(time_values) | np.isnan(current_values))
                            if np.sum(mask) > 1:
                                time_clean = time_values[mask]
                                current_clean = current_values[mask]

                                # Simple capacity calculation
                                time_diff = np.diff(time_clean)
                                current_avg = (current_clean[:-1] + current_clean[1:]) / 2
                                capacity = np.sum(np.abs(current_avg) * time_diff) / 3600  # Ah
                                df_cycle['capacity_estimate'] = capacity
                        except:
                            df_cycle['capacity_estimate'] = np.nan

                # Track statistics
                if battery_id not in battery_stats:
                    battery_stats[battery_id] = {
                        'cycles': [],
                        'total_rows': 0,
                        'min_cycle': cycle_in_battery,
                        'max_cycle': cycle_in_battery
                    }

                battery_stats[battery_id]['cycles'].append(cycle_in_battery)
                battery_stats[battery_id]['total_rows'] += len(df_cycle)
                battery_stats[battery_id]['min_cycle'] = min(battery_stats[battery_id]['min_cycle'], cycle_in_battery)
                battery_stats[battery_id]['max_cycle'] = max(battery_stats[battery_id]['max_cycle'], cycle_in_battery)

                all_data.append(df_cycle)
                successful_loads += 1

            except Exception as e:
                print(f"  ⚠️ Error loading {filename}: {e}")
                continue

        if all_data:
            # Combine all data
            df_combined = pd.concat(all_data, ignore_index=True)

            print(f"\n✅ Successfully loaded {successful_loads} CSV files")
            print(f"   • Combined shape: {df_combined.shape}")
            print(f"   • Unique batteries: {len(battery_stats)}")

            # Display battery statistics
            print(f"\n📈 Battery Statistics:")
            for battery_id, stats in battery_stats.items():
                print(f"   • {battery_id}: Cycles {stats['min_cycle']}-{stats['max_cycle']} "
                      f"({len(stats['cycles'])} cycles, {stats['total_rows']:,} rows)")

            # Show column information
            print(f"\n🔍 Available Columns:")
            for i, col in enumerate(df_combined.columns):
                dtype = df_combined[col].dtype
                non_null = df_combined[col].count()
                print(f"   {i+1:2d}. {col:30} {str(dtype):15} {non_null:8,} non-null")

            return df_combined
        else:
            print("❌ No data loaded successfully")
            return None

    except Exception as e:
        print(f"❌ Error in load_your_nasa_dataset_fixed: {e}")
        import traceback
        traceback.print_exc()
        return None

def create_synthetic_nasa_dataset():
    """Create synthetic NASA dataset for demonstration"""
    np.random.seed(42)

    # NASA battery IDs and characteristics
    battery_configs = {
        'B0005': {'cycles': 168, 'degradation': 0.0035, 'base_capacity': 1.856},
        'B0006': {'cycles': 168, 'degradation': 0.0032, 'base_capacity': 1.869},
        'B0007': {'cycles': 168, 'degradation': 0.0041, 'base_capacity': 1.885},
        'B0018': {'cycles': 132, 'degradation': 0.0036, 'base_capacity': 1.879}
    }

    all_data = []

    for battery_id, config in battery_configs.items():
        cycles = config['cycles']
        degradation = config['degradation']
        base_capacity = config['base_capacity']

        print(f"Creating {battery_id} with {cycles} cycles...")

        for cycle in range(1, cycles + 1):
            # Number of data points in this cycle
            n_points = np.random.randint(100, 300)
            time = np.linspace(0, 100, n_points)

            # Capacity degradation
            if cycle < 20:
                capacity = base_capacity * (1 - 0.0005 * cycle)
            else:
                capacity = base_capacity * np.exp(-degradation * (cycle - 20))

            # Voltage curve (charge/discharge profile)
            voltage_base = 3.7 + 0.3 * (1 - 2 * np.abs(time/100 - 0.5))
            voltage_measured = voltage_base - 0.001 * cycle + np.random.normal(0, 0.03, n_points)

            # Current profile
            current_measured = np.where(
                time < 30,
                1.5 + 0.3 * np.sin(2 * np.pi * time/30),  # Charging
                -1.8 + 0.2 * np.sin(2 * np.pi * (time-30)/70)  # Discharging
            ) + np.random.normal(0, 0.1, n_points)

            # Temperature
            temperature_measured = 25 + 8 * np.sin(np.pi * time/100) + 0.008 * cycle + np.random.normal(0, 1.5, n_points)

            # Load measurements (slightly different from measured)
            current_load = current_measured * 0.95 + np.random.normal(0, 0.05, n_points)
            voltage_load = voltage_measured * 0.98 + np.random.normal(0, 0.02, n_points)

            # Create cycle dataframe
            cycle_df = pd.DataFrame({
                'Voltage_measured': voltage_measured,
                'Current_measured': current_measured,
                'Temperature_measured': temperature_measured,
                'Current_load': current_load,
                'Voltage_load': voltage_load,
                'Time': time,
                'battery_id': battery_id,
                'cycle': cycle,
                'filename': f'{cycle:05d}.csv',
                'original_cycle_num': cycle,
                'capacity_estimate': capacity + np.random.normal(0, 0.02, n_points)
            })

            all_data.append(cycle_df)

    df_combined = pd.concat(all_data, ignore_index=True)

    print(f"\n✅ Created synthetic NASA dataset")
    print(f"   • Batteries: {list(battery_configs.keys())}")
    print(f"   • Total cycles: {sum(cfg['cycles'] for cfg in battery_configs.values())}")
    print(f"   • Total records: {len(df_combined):,}")

    return df_combined

# Try to load your data
print("="*60)
print("LOADING YOUR NASA DATASET")
print("="*60)

# Try different possible paths
possible_paths = [
    "nasa_battery_data/cleaned_dataset/data",
    "nasa_battery_data/data",
    "cleaned_dataset/data",
    "data",
    "."
]

df_battery = None
data_path = None

for path in possible_paths:
    if os.path.exists(path):
        csv_files = glob.glob(os.path.join(path, "*.csv"))
        if csv_files:
            data_path = path
            print(f"✅ Found CSV files in: {data_path}")
            print(f"   • Number of CSV files: {len(csv_files)}")
            print(f"   • Sample files: {[os.path.basename(f) for f in csv_files[:3]]}")
            break

if data_path:
    print(f"\n📥 Loading data from: {data_path}")
    df_battery = load_your_nasa_dataset_fixed(data_path, max_files=200)
else:
    print("❌ Could not find CSV files in any standard location")

# If loading failed, create synthetic data
if df_battery is None or len(df_battery) == 0:
    print("\n" + "="*60)
    print("CREATING SYNTHETIC NASA DATASET FOR DEMONSTRATION")
    print("="*60)
    df_battery = create_synthetic_nasa_dataset()

# Display final dataset info
print("\n" + "="*60)
print("DATASET SUMMARY")
print("="*60)
print(f"Shape: {df_battery.shape}")
print(f"Columns: {len(df_battery.columns)}")
print(f"\nBattery distribution:")
print(df_battery['battery_id'].value_counts())
print(f"\nCycle ranges per battery:")
for battery in df_battery['battery_id'].unique():
    batt_data = df_battery[df_battery['battery_id'] == battery]
    cycles = batt_data['cycle'].unique()
    print(f"  • {battery}: {len(cycles)} cycles ({min(cycles)}-{max(cycles)})")
print(f"\nSample data columns:")
for col in df_battery.columns[:10]:
    print(f"  • {col}")

print("\n📊 First few rows:")
print(df_battery[['battery_id', 'cycle', 'Voltage_measured', 'Current_measured', 'filename']].head())

# @title **Step 4: Create NASA Synthetic Data (Fallback)**
def create_nasa_synthetic_data():
    """
    Create realistic NASA battery data matching the actual dataset structure
    """
    np.random.seed(42)

    # NASA battery IDs from the actual dataset
    battery_ids = ['B0005', 'B0006', 'B0007', 'B0018']

    all_cycles = []

    for battery_id in battery_ids:
        # NASA dataset characteristics
        if battery_id == 'B0005':
            initial_capacity = 1.856
            degradation_rate = 0.0038
            max_cycles = 168
            ir_base = 0.05
        elif battery_id == 'B0006':
            initial_capacity = 1.869
            degradation_rate = 0.0032
            max_cycles = 168
            ir_base = 0.048
        elif battery_id == 'B0007':
            initial_capacity = 1.885
            degradation_rate = 0.0041
            max_cycles = 168
            ir_base = 0.052
        else:  # B0018
            initial_capacity = 1.879
            degradation_rate = 0.0035
            max_cycles = 132
            ir_base = 0.049

        for cycle in range(1, max_cycles + 1):
            # Number of measurements in this cycle
            n_samples = np.random.randint(100, 300)

            # Create time points (0 to 100 minutes for a cycle)
            time = np.linspace(0, 100, n_samples)

            # Capacity for this cycle (degrading over cycles)
            if cycle < 20:
                # Initial stabilization phase
                base_capacity = initial_capacity * (1 - 0.0005 * cycle)
            else:
                # Exponential degradation
                base_capacity = initial_capacity * np.exp(-degradation_rate * (cycle - 20))

            # Add measurement noise
            capacity = base_capacity + np.random.normal(0, 0.015, n_samples)

            # Voltage curve (typical charge/discharge profile)
            # Charge phase (0-30 minutes): voltage rises
            # Discharge phase (30-100 minutes): voltage drops
            voltage_charge = 3.6 + 0.4 * (time[time <= 30] / 30)
            voltage_discharge = 4.0 - 0.5 * ((time[time > 30] - 30) / 70)

            voltage = np.concatenate([voltage_charge, voltage_discharge])
            # Add noise and cycle degradation
            voltage += np.random.normal(0, 0.03, n_samples) - 0.001 * cycle

            # Current profile
            current_charge = 1.5 + 0.3 * np.sin(2 * np.pi * time[time <= 30] / 15)
            current_discharge = -1.8 + 0.2 * np.sin(2 * np.pi * (time[time > 30] - 30) / 35)
            current = np.concatenate([current_charge, current_discharge])

            # Temperature profile
            temperature = 25 + 8 * np.sin(np.pi * time / 100) + 0.008 * cycle
            temperature += np.random.normal(0, 1.5, n_samples)

            # Internal resistance (increases with cycles)
            internal_resistance = ir_base + 0.00035 * cycle + np.random.normal(0, 0.002, n_samples)

            # Additional NASA metrics
            power = voltage * np.abs(current)
            energy = np.cumsum(power) * (100 / n_samples) / 3600  # Wh

            # Create cycle dataframe with NASA-like column names
            cycle_df = pd.DataFrame({
                'Time': time,
                'Voltage_measured': voltage,
                'Current_measured': current,
                'Temperature_measured': temperature,
                'Capacity': capacity,
                'Internal_resistance': internal_resistance,
                'Power': power,
                'Energy': energy,
                'Voltage_load': voltage - internal_resistance * current,
                'Current_load': current,
                'battery_id': battery_id,
                'cycle': cycle,
                'filename': f'{battery_id}_cycle{cycle}.csv'
            })

            all_cycles.append(cycle_df)

    # Combine all cycles
    df_combined = pd.concat(all_cycles, ignore_index=True)

    print(f"✅ Created realistic NASA-style dataset")
    print(f"   • Total records: {len(df_combined):,}")
    print(f"   • Batteries: {battery_ids}")
    print(f"   • Total cycles: {sum([168, 168, 168, 132])}")
    print(f"   • Columns: {df_combined.columns.tolist()}")

    return df_combined

# If df_battery is still None, create it
if df_battery is None:
    df_battery = create_nasa_synthetic_data()

print("\n📊 Dataset Preview:")
print(df_battery.head())
print(f"\n📈 Dataset Statistics:")
print(f"Shape: {df_battery.shape}")
print(f"Memory usage: {df_battery.memory_usage().sum() / 1024 / 1024:.1f} MB")
print(f"Unique batteries: {df_battery['battery_id'].nunique()}")
print(f"Total cycles: {df_battery['cycle'].nunique()}")

# @title **Step 5: Feature Engineering - NASA Battery Health Metrics**
print("🔧 Engineering NASA battery health features...")

# First, normalize column names (different CSV files might have different naming)
# Convert all column names to lowercase for consistency
df_battery.columns = [col.lower().replace(' ', '_') for col in df_battery.columns]

print("📋 Standardized column names:")
for i, col in enumerate(df_battery.columns):
    print(f"  {i+1:2d}. {col}")

# Group data by battery and cycle for feature engineering
features_by_battery = []

for battery_id in df_battery['battery_id'].unique():
    battery_data = df_battery[df_battery['battery_id'] == battery_id].copy()

    # Sort by cycle and time
    if 'time' in battery_data.columns:
        battery_data = battery_data.sort_values(['cycle', 'time'])
    else:
        # Find time-like column
        time_cols = [col for col in battery_data.columns if 'time' in col.lower()]
        if time_cols:
            battery_data = battery_data.sort_values(['cycle', time_cols[0]])
        else:
            battery_data = battery_data.sort_values('cycle')

    # Calculate cycle-level aggregates
    cycle_stats = []
    cycles_processed = 0

    for cycle in battery_data['cycle'].unique():
        cycle_data = battery_data[battery_data['cycle'] == cycle]

        if len(cycle_data) > 5:  # Only process cycles with enough data
            # Initialize stats dictionary
            stats = {
                'battery_id': battery_id,
                'cycle': int(cycle),
                'data_points': len(cycle_data)
            }

            # Extract key metrics if columns exist
            metrics_to_calculate = {
                'capacity': ['mean', 'min', 'max', 'std'],
                'voltage_measured': ['mean', 'min', 'max', 'std'],
                'current_measured': ['mean', 'min', 'max', 'std'],
                'temperature_measured': ['mean', 'max', 'std'],
                'internal_resistance': ['mean', 'max', 'std'],
                'power': ['mean', 'max'],
                'energy': ['max']
            }

            for metric, operations in metrics_to_calculate.items():
                if metric in cycle_data.columns:
                    for op in operations:
                        if op == 'mean':
                            stats[f'{metric}_mean'] = cycle_data[metric].mean()
                        elif op == 'min':
                            stats[f'{metric}_min'] = cycle_data[metric].min()
                        elif op == 'max':
                            stats[f'{metric}_max'] = cycle_data[metric].max()
                        elif op == 'std':
                            stats[f'{metric}_std'] = cycle_data[metric].std()

            # Calculate discharge metrics if we have time and current data
            if 'time' in cycle_data.columns and 'current_measured' in cycle_data.columns:
                # Find discharge phase (negative current)
                discharge_mask = cycle_data['current_measured'] < -0.5
                if discharge_mask.sum() > 5:
                    discharge_data = cycle_data[discharge_mask]

                    # Discharge capacity (Ah) - integrate current over time
                    if len(discharge_data) > 1:
                        time_diff = np.diff(discharge_data['time'].values)
                        current_avg = (discharge_data['current_measured'].values[:-1] +
                                      discharge_data['current_measured'].values[1:]) / 2
                        discharge_capacity = np.sum(np.abs(current_avg) * time_diff) / 3600  # Convert to Ah
                        stats['discharge_capacity'] = discharge_capacity

                        # Voltage drop during discharge
                        if 'voltage_measured' in discharge_data.columns:
                            stats['voltage_drop'] = (
                                discharge_data['voltage_measured'].iloc[0] -
                                discharge_data['voltage_measured'].iloc[-1]
                            )

            cycle_stats.append(stats)
            cycles_processed += 1

    if cycle_stats:
        # Create cycle-level dataframe
        cycle_df = pd.DataFrame(cycle_stats)

        # Sort by cycle
        cycle_df = cycle_df.sort_values('cycle')

        # Calculate State of Health (SOH)
        if 'capacity_mean' in cycle_df.columns:
            initial_capacity = cycle_df['capacity_mean'].iloc[:5].mean()
            cycle_df['soh'] = (cycle_df['capacity_mean'] / initial_capacity) * 100

        # Calculate degradation rates
        if 'capacity_mean' in cycle_df.columns:
            cycle_df['capacity_fade_rate'] = -cycle_df['capacity_mean'].diff(5).rolling(window=3, center=True).mean()

        if 'internal_resistance_mean' in cycle_df.columns:
            cycle_df['ir_growth_rate'] = cycle_df['internal_resistance_mean'].diff(5).rolling(window=3, center=True).mean()

        # Calculate temperature increase
        if 'temperature_max' in cycle_df.columns:
            cycle_df['temp_increase'] = cycle_df['temperature_max'].diff(10).rolling(window=5, center=True).mean()

        # Calculate health score (composite metric)
        health_components = []
        weights = []

        if 'soh' in cycle_df.columns:
            health_components.append(cycle_df['soh'] / 100)
            weights.append(0.40)

        if 'capacity_fade_rate' in cycle_df.columns:
            # Lower fade rate is better
            fade_score = 1 - (cycle_df['capacity_fade_rate'].abs().clip(0, 0.02) / 0.02)
            health_components.append(fade_score)
            weights.append(0.20)

        if 'ir_growth_rate' in cycle_df.columns:
            # Lower IR growth is better
            ir_score = 1 - (cycle_df['ir_growth_rate'].clip(0, 0.001) / 0.001)
            health_components.append(ir_score)
            weights.append(0.20)

        if 'temp_increase' in cycle_df.columns:
            # Lower temperature increase is better
            temp_score = 1 - (cycle_df['temp_increase'].clip(0, 0.5) / 0.5)
            health_components.append(temp_score)
            weights.append(0.10)

        if 'voltage_drop' in cycle_df.columns:
            # Lower voltage drop is better
            voltage_score = 1 - (cycle_df['voltage_drop'].clip(0, 0.3) / 0.3)
            health_components.append(voltage_score)
            weights.append(0.10)

        if health_components and weights:
            # Normalize weights to sum to 1
            total_weight = sum(weights)
            weights = [w/total_weight for w in weights]

            # Calculate weighted health score
            health_score = sum(comp * weight for comp, weight in zip(health_components, weights))
            cycle_df['health_score'] = health_score * 100
        else:
            # Fallback if we don't have enough components
            cycle_df['health_score'] = cycle_df.get('soh', 100)

        # Calculate Remaining Useful Life (RUL)
        cycle_df['rul'] = np.nan

        # Method 1: Find when health score drops below 70%
        critical_cycles = cycle_df[cycle_df['health_score'] < 70]
        if len(critical_cycles) > 0:
            eol_cycle = critical_cycles['cycle'].iloc[0]
            cycle_df['rul'] = eol_cycle - cycle_df['cycle']
        else:
            # Method 2: Linear extrapolation based on recent trend
            if len(cycle_df) > 30:
                recent_health = cycle_df['health_score'].iloc[-30:].values
                cycles_idx = np.arange(len(recent_health))

                if len(np.unique(recent_health)) > 1:
                    # Fit linear regression
                    slope, intercept = np.polyfit(cycles_idx, recent_health, 1)

                    if slope < 0:  # Only if degrading
                        cycles_to_eol = (70 - intercept) / abs(slope)
                        cycle_df['rul'] = cycles_to_eol - (len(cycle_df) - 30) + cycles_idx
                    else:
                        # If not degrading, set conservative estimate
                        cycle_df['rul'] = 200 - cycle_df['cycle']
                else:
                    cycle_df['rul'] = 150 - cycle_df['cycle']
            else:
                cycle_df['rul'] = 100 - cycle_df['cycle']

        # Ensure RUL is non-negative
        cycle_df['rul'] = cycle_df['rul'].clip(lower=0)

        features_by_battery.append(cycle_df)

        print(f"  • Processed {cycles_processed} cycles for {battery_id}")

# Combine all battery features
if features_by_battery:
    df_features = pd.concat(features_by_battery, ignore_index=True)

    # Fill NaN values
    numeric_cols = df_features.select_dtypes(include=[np.number]).columns
    for col in numeric_cols:
        df_features[col] = df_features[col].fillna(method='ffill').fillna(method='bfill')

    print(f"\n✅ Feature engineering complete!")
    print(f"   • Total cycles analyzed: {len(df_features)}")
    print(f"   • Features created: {len(df_features.columns)}")
    print(f"   • Key metrics: Health Score, RUL, SOH, Capacity Fade Rate")

    print("\n📋 Sample of engineered features:")
    sample_cols = ['battery_id', 'cycle', 'data_points']
    if 'capacity_mean' in df_features.columns:
        sample_cols.append('capacity_mean')
    if 'soh' in df_features.columns:
        sample_cols.append('soh')
    if 'health_score' in df_features.columns:
        sample_cols.append('health_score')
    if 'rul' in df_features.columns:
        sample_cols.append('rul')

    print(df_features[sample_cols].head(10))
else:
    print("❌ No features were engineered")
    # Create minimal features for demonstration
    df_features = pd.DataFrame({
        'battery_id': df_battery['battery_id'].unique().repeat(10),
        'cycle': np.tile(range(1, 11), len(df_battery['battery_id'].unique())),
        'health_score': np.random.uniform(60, 100, len(df_battery['battery_id'].unique()) * 10),
        'rul': np.random.uniform(20, 150, len(df_battery['battery_id'].unique()) * 10),
        'soh': np.random.uniform(65, 100, len(df_battery['battery_id'].unique()) * 10)
    })

# @title **Step 5: Feature Engineering - NASA Battery Health Metrics (FIXED)**
print("🔧 Engineering NASA battery health features...")

# First, let's check the data types of our columns
print("🔍 Checking data types in battery data:")
print(df_battery.dtypes.head(20))

# Convert any object/string columns to numeric where possible
for col in df_battery.select_dtypes(include=['object']).columns:
    if col not in ['battery_id', 'filename']:  # Don't convert ID columns
        try:
            df_battery[col] = pd.to_numeric(df_battery[col], errors='coerce')
            print(f"  ✅ Converted {col} to numeric")
        except:
            print(f"  ⚠️ Could not convert {col} to numeric")

# Also check for any numeric columns stored as strings
for col in df_battery.columns:
    if df_battery[col].dtype == 'object':
        # Try to see if it's actually numeric
        sample = df_battery[col].dropna().head(5)
        if all(isinstance(x, (int, float)) or (isinstance(x, str) and x.replace('.', '', 1).isdigit()) for x in sample if pd.notnull(x)):
            try:
                df_battery[col] = pd.to_numeric(df_battery[col], errors='coerce')
                print(f"  ✅ Converted {col} to numeric")
            except:
                pass

# Now let's identify which columns are numeric
numeric_cols = df_battery.select_dtypes(include=[np.number]).columns
print(f"\n📊 Found {len(numeric_cols)} numeric columns:")
print(list(numeric_cols))

# Group data by battery and cycle for feature engineering
features_by_battery = []

for battery_id in df_battery['battery_id'].unique():
    battery_data = df_battery[df_battery['battery_id'] == battery_id].copy()

    print(f"\n📈 Processing {battery_id}...")

    # Sort by cycle and time (if available)
    time_col = None
    time_cols = [col for col in battery_data.columns if 'time' in col.lower()]
    if time_cols:
        time_col = time_cols[0]
        battery_data = battery_data.sort_values(['cycle', time_col])
    else:
        battery_data = battery_data.sort_values('cycle')

    # Calculate cycle-level aggregates
    cycle_stats = []
    cycles_processed = 0

    for cycle in battery_data['cycle'].unique():
        cycle_data = battery_data[battery_data['cycle'] == cycle]

        if len(cycle_data) > 5:  # Only process cycles with enough data
            stats = {
                'battery_id': battery_id,
                'cycle': int(cycle),
                'data_points': len(cycle_data)
            }

            # Extract key metrics from numeric columns
            potential_metrics = {
                'capacity': ['mean', 'min', 'max', 'std'],
                'voltage': ['mean', 'min', 'max', 'std'],
                'current': ['mean', 'min', 'max', 'std'],
                'temperature': ['mean', 'max', 'std'],
                'power': ['mean', 'max'],
                'energy': ['max'],
                'soc': ['mean', 'std'],  # State of Charge
                'soh': ['mean'],  # State of Health if available
                'ir': ['mean', 'max']  # Internal Resistance
            }

            # Check which columns we actually have
            available_metrics = {}
            for metric_base, operations in potential_metrics.items():
                # Find matching columns (case insensitive, partial match)
                matching_cols = [col for col in numeric_cols if metric_base.lower() in col.lower()]
                if matching_cols:
                    # Use the first matching column
                    col_name = matching_cols[0]
                    available_metrics[col_name] = operations
                    # Also add the base name for reference
                    available_metrics[metric_base] = operations

            # Calculate statistics for available metrics
            for metric, operations in available_metrics.items():
                if metric in cycle_data.columns:
                    # Ensure it's numeric
                    if cycle_data[metric].dtype in [np.int64, np.float64]:
                        for op in operations:
                            col_name = f"{metric}_{op}"
                            try:
                                if op == 'mean':
                                    stats[col_name] = float(cycle_data[metric].mean())
                                elif op == 'min':
                                    stats[col_name] = float(cycle_data[metric].min())
                                elif op == 'max':
                                    stats[col_name] = float(cycle_data[metric].max())
                                elif op == 'std':
                                    stats[col_name] = float(cycle_data[metric].std())
                            except Exception as e:
                                stats[col_name] = np.nan
                    else:
                        # Try to convert to numeric
                        try:
                            numeric_series = pd.to_numeric(cycle_data[metric], errors='coerce')
                            for op in operations:
                                col_name = f"{metric}_{op}"
                                try:
                                    if op == 'mean':
                                        stats[col_name] = float(numeric_series.mean())
                                    elif op == 'min':
                                        stats[col_name] = float(numeric_series.min())
                                    elif op == 'max':
                                        stats[col_name] = float(numeric_series.max())
                                    elif op == 'std':
                                        stats[col_name] = float(numeric_series.std())
                                except:
                                    stats[col_name] = np.nan
                        except:
                            pass

            # Try to find capacity-related columns
            capacity_cols = [col for col in cycle_data.columns if 'capacity' in col.lower()]
            if capacity_cols:
                capacity_col = capacity_cols[0]
                if capacity_col in cycle_data.columns:
                    try:
                        stats['capacity'] = float(cycle_data[capacity_col].mean())
                    except:
                        # Try conversion
                        try:
                            numeric_capacity = pd.to_numeric(cycle_data[capacity_col], errors='coerce')
                            stats['capacity'] = float(numeric_capacity.mean())
                        except:
                            pass

            # Try to find voltage-related columns
            voltage_cols = [col for col in cycle_data.columns if 'voltage' in col.lower()]
            if voltage_cols:
                voltage_col = voltage_cols[0]
                if voltage_col in cycle_data.columns:
                    try:
                        stats['voltage'] = float(cycle_data[voltage_col].mean())
                    except:
                        try:
                            numeric_voltage = pd.to_numeric(cycle_data[voltage_col], errors='coerce')
                            stats['voltage'] = float(numeric_voltage.mean())
                        except:
                            pass

            # Try to find temperature-related columns
            temp_cols = [col for col in cycle_data.columns if 'temp' in col.lower() or 'temperature' in col.lower()]
            if temp_cols:
                temp_col = temp_cols[0]
                if temp_col in cycle_data.columns:
                    try:
                        stats['temperature'] = float(cycle_data[temp_col].mean())
                    except:
                        try:
                            numeric_temp = pd.to_numeric(cycle_data[temp_col], errors='coerce')
                            stats['temperature'] = float(numeric_temp.mean())
                        except:
                            pass

            cycle_stats.append(stats)
            cycles_processed += 1

    if cycle_stats:
        # Create cycle-level dataframe
        try:
            cycle_df = pd.DataFrame(cycle_stats)

            # Sort by cycle
            cycle_df = cycle_df.sort_values('cycle').reset_index(drop=True)

            print(f"  ✅ Processed {cycles_processed} cycles for {battery_id}")

            # Calculate State of Health (SOH) if we have capacity data
            if 'capacity' in cycle_df.columns:
                initial_capacity = cycle_df['capacity'].iloc[:5].mean()
                if initial_capacity > 0:
                    cycle_df['soh'] = (cycle_df['capacity'] / initial_capacity) * 100

            # Calculate degradation rates
            if 'capacity' in cycle_df.columns:
                # Capacity fade rate (negative means capacity is decreasing)
                cycle_df['capacity_fade_rate'] = -cycle_df['capacity'].diff(5).rolling(window=3, center=True).mean()

            # Calculate health score (composite metric)
            health_score = np.zeros(len(cycle_df))

            # Component 1: Capacity/SOH (40% weight)
            if 'soh' in cycle_df.columns:
                soh_component = cycle_df['soh'].fillna(100) / 100
                health_score += soh_component * 0.4
            elif 'capacity' in cycle_df.columns:
                capacity_norm = cycle_df['capacity'] / cycle_df['capacity'].max()
                health_score += capacity_norm * 0.4

            # Component 2: Voltage stability (20% weight)
            if 'voltage_std' in cycle_df.columns:
                voltage_stability = 1 - (cycle_df['voltage_std'].fillna(0) / 0.1).clip(0, 1)
                health_score += voltage_stability * 0.2
            elif 'voltage' in cycle_df.columns:
                # Use coefficient of variation
                voltage_cv = cycle_df['voltage'].rolling(10).std() / cycle_df['voltage'].rolling(10).mean()
                voltage_stability = 1 - voltage_cv.fillna(0).clip(0, 1)
                health_score += voltage_stability * 0.2

            # Component 3: Temperature stability (20% weight)
            if 'temperature_std' in cycle_df.columns:
                temp_stability = 1 - (cycle_df['temperature_std'].fillna(0) / 5).clip(0, 1)
                health_score += temp_stability * 0.2
            elif 'temperature' in cycle_df.columns:
                # Normalize temperature (assume 20-40°C is optimal)
                temp_norm = 1 - ((cycle_df['temperature'] - 30).abs() / 20).clip(0, 1)
                health_score += temp_norm * 0.2

            # Component 4: Data quality (20% weight) - more data points = better
            data_quality = cycle_df['data_points'] / cycle_df['data_points'].max()
            health_score += data_quality * 0.2

            # Ensure health score is between 0 and 100
            cycle_df['health_score'] = np.clip(health_score * 100, 0, 100)

            # Calculate Remaining Useful Life (RUL)
            cycle_df['rul'] = np.nan

            # Find when health score drops below 70%
            critical_mask = cycle_df['health_score'] < 70
            if critical_mask.any():
                first_critical = cycle_df[critical_mask]['cycle'].iloc[0]
                cycle_df['rul'] = first_critical - cycle_df['cycle']
            else:
                # Linear extrapolation based on health trend
                if len(cycle_df) > 10:
                    # Fit trend to last 10 cycles
                    last_10 = cycle_df['health_score'].iloc[-10:].values
                    if len(np.unique(last_10)) > 1:
                        x = np.arange(len(last_10))
                        slope, intercept = np.polyfit(x, last_10, 1)

                        if slope < 0:  # If degrading
                            cycles_to_70 = (70 - intercept) / abs(slope)
                            cycle_df['rul'] = cycles_to_70 - (len(cycle_df) - 10) + x
                        else:
                            cycle_df['rul'] = 200 - cycle_df['cycle']
                    else:
                        cycle_df['rul'] = 150 - cycle_df['cycle']
                else:
                    cycle_df['rul'] = 100 - cycle_df['cycle']

            # Ensure RUL is non-negative
            cycle_df['rul'] = cycle_df['rul'].clip(lower=0)

            features_by_battery.append(cycle_df)

        except Exception as e:
            print(f"  ❌ Error processing {battery_id}: {e}")
            continue
    else:
        print(f"  ⚠️ No cycles processed for {battery_id}")

# Combine all battery features
if features_by_battery:
    try:
        df_features = pd.concat(features_by_battery, ignore_index=True)

        # Fill NaN values
        numeric_cols_features = df_features.select_dtypes(include=[np.number]).columns
        for col in numeric_cols_features:
            df_features[col] = df_features[col].fillna(method='ffill').fillna(method='bfill')

        print(f"\n✅ Feature engineering complete!")
        print(f"   • Total cycles analyzed: {len(df_features)}")
        print(f"   • Features created: {len(df_features.columns)}")

        print("\n📋 Sample of engineered features:")
        # Show available columns
        available_cols = list(df_features.columns)
        print(f"Available columns: {len(available_cols)}")

        # Show first few columns
        print("\nFirst 10 columns:")
        for i, col in enumerate(available_cols[:10]):
            print(f"  {i+1}. {col}")

        # Show sample data
        sample_cols = ['battery_id', 'cycle', 'data_points']
        if 'health_score' in df_features.columns:
            sample_cols.append('health_score')
        if 'rul' in df_features.columns:
            sample_cols.append('rul')
        if 'soh' in df_features.columns:
            sample_cols.append('soh')

        print(f"\nSample data with columns: {sample_cols}")
        print(df_features[sample_cols].head(10))

    except Exception as e:
        print(f"❌ Error combining features: {e}")
        df_features = None
else:
    print("❌ No features were engineered")
    df_features = None

# If df_features is None, create a minimal version for demonstration
if df_features is None:
    print("\n⚠️ Creating minimal features for demonstration...")

    # Create simple features for demonstration
    all_cycles = []
    for battery_id in df_battery['battery_id'].unique():
        max_cycle = df_battery[df_battery['battery_id'] == battery_id]['cycle'].max()

        for cycle in range(1, min(100, max_cycle + 1)):
            # Create synthetic health metrics
            health = 100 - (cycle * 0.3) + np.random.normal(0, 5)
            health = max(30, min(100, health))

            rul = max(0, 150 - cycle + np.random.normal(0, 10))

            all_cycles.append({
                'battery_id': battery_id,
                'cycle': cycle,
                'health_score': health,
                'rul': rul,
                'soh': health,  # SOH similar to health score
                'data_points': np.random.randint(50, 200)
            })

    df_features = pd.DataFrame(all_cycles)

    print(f"✅ Created minimal features with {len(df_features)} records")
    print(df_features.head())

print("\n" + "="*60)
print("FEATURE ENGINEERING SUMMARY")
print("="*60)
print(f"• df_features shape: {df_features.shape if df_features is not None else 'Not available'}")
print(f"• Columns available: {list(df_features.columns) if df_features is not None else 'None'}")
print(f"• Batteries: {df_features['battery_id'].nunique() if df_features is not None else 0}")
print(f"• Total cycles: {len(df_features) if df_features is not None else 0}")

# @title **Step 6: NASA Battery Health Dashboard - MULTI-BATTERY VERSION**
print("📊 Creating NASA Battery Health Dashboard for ALL batteries...")

# First, ensure df_features exists and has data
if df_features is None or len(df_features) == 0:
    print("❌ df_features is empty. Creating emergency multi-battery dataset...")

    # Create comprehensive emergency dataset
    emergency_data = []
    battery_ids = df_battery['battery_id'].unique()

    print(f"🔋 Creating data for {len(battery_ids)} batteries: {list(battery_ids)}")

    for battery_id in battery_ids:
        # Different degradation patterns for different batteries
        if 'B0005' in battery_id:
            base_health = 100
            degradation_rate = 0.25
            base_capacity = 1.856
        elif 'B0006' in battery_id:
            base_health = 98
            degradation_rate = 0.22
            base_capacity = 1.869
        elif 'B0007' in battery_id:
            base_health = 95
            degradation_rate = 0.28
            base_capacity = 1.885
        elif 'B0018' in battery_id:
            base_health = 96
            degradation_rate = 0.20
            base_capacity = 1.879
        else:
            base_health = 100
            degradation_rate = 0.30
            base_capacity = 1.850

        max_cycles = min(168, df_battery[df_battery['battery_id'] == battery_id]['cycle'].max() if len(df_battery) > 0 else 100)

        for cycle in range(1, max_cycles + 1):
            # Create realistic degradation with variations
            health = base_health - (cycle * degradation_rate) + np.random.normal(0, 3)
            health = max(30, min(100, health))

            rul = max(0, 168 - cycle + np.random.normal(0, 15))

            capacity = base_capacity * (health / 100)

            emergency_data.append({
                'battery_id': battery_id,
                'cycle': cycle,
                'health_score': health,
                'rul': rul,
                'soh': health * 0.95,  # SOH similar to health
                'capacity': capacity,
                'voltage_mean': 3.7 - (cycle * 0.001),
                'temperature_mean': 25 + (cycle * 0.02),
                'internal_resistance': 0.05 + (cycle * 0.0002),
                'capacity_fade_rate': -degradation_rate/100  # Ah/cycle
            })

    df_features = pd.DataFrame(emergency_data)
    print(f"✅ Created multi-battery dataset with {len(df_features)} records for {len(battery_ids)} batteries")

# Show statistics about our dataset
print("\n" + "="*60)
print("DATASET STATISTICS")
print("="*60)
print(f"• Total batteries: {df_features['battery_id'].nunique()}")
print(f"• Total cycles: {len(df_features)}")
print(f"• Average cycles per battery: {len(df_features) / df_features['battery_id'].nunique():.0f}")
print(f"• Available batteries: {list(df_features['battery_id'].unique())}")
print(f"• Available columns: {list(df_features.columns)}")

# Get ALL batteries
all_batteries = df_features['battery_id'].unique()
print(f"\n📈 Creating dashboard for ALL {len(all_batteries)} batteries")

# Create a color palette for all batteries
colors = plt.cm.tab20(np.linspace(0, 1, len(all_batteries)))

# Create a comprehensive dashboard
plt.style.use('seaborn-v0_8-darkgrid')
fig = plt.figure(figsize=(22, 18))
fig.suptitle('NASA Battery Fleet: Complete Predictive Maintenance Dashboard',
             fontsize=24, fontweight='bold', y=0.98)

# Create grid layout
gs = fig.add_gridspec(4, 4, hspace=0.35, wspace=0.3)

# PLOT 1: Health Score Timeline for ALL Batteries
ax1 = fig.add_subplot(gs[0, :2])  # Top-left, spans 2 columns
for idx, battery in enumerate(all_batteries):
    batt_data = df_features[df_features['battery_id'] == battery].sort_values('cycle')
    ax1.plot(batt_data['cycle'], batt_data['health_score'],
            color=colors[idx], linewidth=2.5, label=battery, alpha=0.9)

# Add health zones
ax1.axhspan(0, 70, facecolor='red', alpha=0.15, label='Critical Zone (<70%)')
ax1.axhspan(70, 85, facecolor='orange', alpha=0.15, label='Warning Zone (70-85%)')
ax1.axhspan(85, 100, facecolor='green', alpha=0.15, label='Healthy Zone (>85%)')
ax1.axhline(y=70, color='red', linestyle='--', linewidth=2, alpha=0.7)
ax1.axhline(y=85, color='orange', linestyle='--', linewidth=2, alpha=0.7)

ax1.set_xlabel('Cycle Number', fontsize=12, fontweight='bold')
ax1.set_ylabel('Health Score (%)', fontsize=12, fontweight='bold')
ax1.set_title('Fleet Health Score Timeline', fontsize=14, fontweight='bold')
ax1.legend(loc='upper right', fontsize=10, ncol=2)
ax1.grid(True, alpha=0.3)
ax1.set_ylim(40, 105)

# PLOT 2: RUL Projection for ALL Batteries
ax2 = fig.add_subplot(gs[0, 2:])  # Top-right, spans 2 columns
for idx, battery in enumerate(all_batteries):
    batt_data = df_features[df_features['battery_id'] == battery].sort_values('cycle')
    ax2.plot(batt_data['cycle'], batt_data['rul'],
            color=colors[idx], linewidth=2.5, label=battery, alpha=0.9)

# Add maintenance thresholds
ax2.axhline(y=50, color='orange', linestyle='--', linewidth=2, alpha=0.7, label='Plan Maintenance (50 cycles)')
ax2.axhline(y=20, color='red', linestyle='--', linewidth=2, alpha=0.7, label='Immediate Action (20 cycles)')
ax2.fill_between([0, 200], 0, 20, color='red', alpha=0.15)
ax2.fill_between([0, 200], 20, 50, color='orange', alpha=0.15)

ax2.set_xlabel('Current Cycle', fontsize=12, fontweight='bold')
ax2.set_ylabel('Remaining Useful Life (Cycles)', fontsize=12, fontweight='bold')
ax2.set_title('RUL Projection - All Batteries', fontsize=14, fontweight='bold')
ax2.legend(loc='upper right', fontsize=10, ncol=2)
ax2.grid(True, alpha=0.3)

# PLOT 3: Current Health Status - Horizontal Bar Chart
ax3 = fig.add_subplot(gs[1, :2])  # Second row, left

# Get current status for all batteries
current_status = []
for battery in all_batteries:
    batt_data = df_features[df_features['battery_id'] == battery]
    if len(batt_data) > 0:
        latest = batt_data.iloc[-1]
        current_status.append({
            'battery': battery,
            'cycle': latest['cycle'],
            'health': latest['health_score'],
            'rul': latest['rul'],
            'status': 'CRITICAL' if latest['health_score'] < 70 else
                     'WARNING' if latest['health_score'] < 85 else
                     'HEALTHY'
        })

status_df = pd.DataFrame(current_status).sort_values('health')

# Create horizontal bar chart
bars = ax3.barh(range(len(status_df)), status_df['health'],
               color=['red' if s == 'CRITICAL' else 'orange' if s == 'WARNING' else 'green'
                      for s in status_df['status']],
               alpha=0.8, edgecolor='black')

ax3.set_yticks(range(len(status_df)))
ax3.set_yticklabels(status_df['battery'])
ax3.set_xlabel('Current Health Score (%)', fontsize=12, fontweight='bold')
ax3.set_title('Current Battery Health Status', fontsize=14, fontweight='bold')

# Add health values on bars
for i, (bar, health) in enumerate(zip(bars, status_df['health'])):
    ax3.text(bar.get_width() + 0.5, bar.get_y() + bar.get_height()/2,
            f'{health:.1f}%', va='center', fontsize=10, fontweight='bold')

    # Add RUL info
    rul = status_df['rul'].iloc[i]
    ax3.text(5, bar.get_y() + bar.get_height()/2,
            f'RUL: {rul:.0f} cycles', va='center', fontsize=9, color='white', fontweight='bold')

ax3.grid(True, alpha=0.3, axis='x')
ax3.set_xlim(0, 105)

# PLOT 4: Capacity Comparison (if available)
ax4 = fig.add_subplot(gs[1, 2:])  # Second row, right
if 'capacity' in df_features.columns:
    for idx, battery in enumerate(all_batteries):
        batt_data = df_features[df_features['battery_id'] == battery].sort_values('cycle')
        ax4.plot(batt_data['cycle'], batt_data['capacity'],
                color=colors[idx], linewidth=2, label=battery, alpha=0.8)

    ax4.axhline(y=1.3, color='red', linestyle='--', linewidth=2, alpha=0.7, label='EOL Threshold (1.3Ah)')
    ax4.set_xlabel('Cycle Number', fontsize=12, fontweight='bold')
    ax4.set_ylabel('Capacity (Ah)', fontsize=12, fontweight='bold')
    ax4.set_title('Battery Capacity Degradation Comparison', fontsize=14, fontweight='bold')
    ax4.legend(loc='upper right', fontsize=10, ncol=2)
else:
    # Use health as proxy
    for idx, battery in enumerate(all_batteries):
        batt_data = df_features[df_features['battery_id'] == battery].sort_values('cycle')
        ax4.plot(batt_data['cycle'], batt_data['health_score']/100 * 1.8,
                color=colors[idx], linewidth=2, label=battery, alpha=0.8)

    ax4.set_xlabel('Cycle Number', fontsize=12, fontweight='bold')
    ax4.set_ylabel('Capacity (Ah) - Estimated', fontsize=12, fontweight='bold')
    ax4.set_title('Estimated Capacity Degradation', fontsize=14, fontweight='bold')
    ax4.legend(loc='upper right', fontsize=10, ncol=2)

ax4.grid(True, alpha=0.3)

# PLOT 5: Maintenance Priority Timeline
ax5 = fig.add_subplot(gs[2, :])  # Third row, spans all columns

# Calculate maintenance needs
maintenance_timeline = []
for battery in all_batteries:
    batt_data = df_features[df_features['battery_id'] == battery].sort_values('cycle')
    if len(batt_data) > 0:
        latest = batt_data.iloc[-1]
        health = latest['health_score']
        rul = latest['rul']

        # Determine priority
        if health < 70 or rul < 20:
            priority = 'IMMEDIATE'
            color = 'red'
            days = 7
        elif health < 80 or rul < 50:
            priority = 'URGENT'
            color = 'orange'
            days = 30
        elif health < 90 or rul < 100:
            priority = 'PLAN'
            color = 'yellow'
            days = 60
        else:
            priority = 'MONITOR'
            color = 'green'
            days = 90

        maintenance_timeline.append({
            'battery': battery,
            'priority': priority,
            'color': color,
            'days_until_action': days,
            'current_health': health,
            'current_rul': rul
        })

maint_df = pd.DataFrame(maintenance_timeline).sort_values('days_until_action')

# Create Gantt-style chart
y_pos = range(len(maint_df))
bar_height = 0.6

for i, (idx, row) in enumerate(maint_df.iterrows()):
    ax5.barh(i, row['days_until_action'], height=bar_height,
            color=row['color'], alpha=0.8, edgecolor='black')

    # Add text labels
    ax5.text(row['days_until_action'] + 2, i,
            f"{row['priority']} (Health: {row['current_health']:.1f}%, RUL: {row['current_rul']:.0f} cycles)",
            va='center', fontsize=10)

ax5.set_yticks(y_pos)
ax5.set_yticklabels(maint_df['battery'])
ax5.set_xlabel('Days Until Required Action', fontsize=12, fontweight='bold')
ax5.set_title('Maintenance Priority & Timeline', fontsize=14, fontweight='bold')
ax5.grid(True, alpha=0.3, axis='x')
ax5.set_xlim(0, 100)

# Add priority legend
priority_handles = [
    plt.Rectangle((0,0),1,1, color='red', alpha=0.8, label='Immediate (< 7 days)'),
    plt.Rectangle((0,0),1,1, color='orange', alpha=0.8, label='Urgent (< 30 days)'),
    plt.Rectangle((0,0),1,1, color='yellow', alpha=0.8, label='Plan (< 60 days)'),
    plt.Rectangle((0,0),1,1, color='green', alpha=0.8, label='Monitor (< 90 days)')
]
ax5.legend(handles=priority_handles, loc='upper right', fontsize=10)

# PLOT 6: Degradation Rate Comparison
ax6 = fig.add_subplot(gs[3, 0])  # Bottom row, first column
if 'capacity_fade_rate' in df_features.columns:
    degradation_rates = []
    battery_labels = []

    for battery in all_batteries:
        batt_data = df_features[df_features['battery_id'] == battery]
        if len(batt_data) > 0:
            avg_fade_rate = batt_data['capacity_fade_rate'].mean()
            degradation_rates.append(avg_fade_rate)
            battery_labels.append(battery)

    # Sort by degradation rate (most negative first)
    sorted_data = sorted(zip(battery_labels, degradation_rates), key=lambda x: x[1])
    sorted_labels = [x[0] for x in sorted_data]
    sorted_rates = [x[1] for x in sorted_data]

    bars = ax6.barh(range(len(sorted_labels)), sorted_rates,
                   color=['red' if r < -0.01 else 'orange' if r < -0.005 else 'green'
                          for r in sorted_rates],
                   alpha=0.8, edgecolor='black')

    ax6.set_yticks(range(len(sorted_labels)))
    ax6.set_yticklabels(sorted_labels)
    ax6.set_xlabel('Average Capacity Fade Rate (Ah/cycle)', fontsize=11)
    ax6.set_title('Degradation Rate Comparison', fontsize=13, fontweight='bold')

    # Add rate values
    for i, (bar, rate) in enumerate(zip(bars, sorted_rates)):
        ax6.text(bar.get_width() + (0.0001 if rate >= 0 else -0.0005),
                bar.get_y() + bar.get_height()/2,
                f'{rate:.4f}', va='center', fontsize=9, fontweight='bold')

    ax6.axvline(x=-0.01, color='red', linestyle='--', alpha=0.5, label='Critical')
    ax6.axvline(x=-0.005, color='orange', linestyle='--', alpha=0.5, label='Warning')

else:
    ax6.text(0.5, 0.5, 'Degradation Rate Data\nNot Available',
            ha='center', va='center', transform=ax6.transAxes, fontsize=12)
    ax6.set_title('Degradation Rate Comparison', fontsize=13, fontweight='bold')

ax6.grid(True, alpha=0.3, axis='x')

# PLOT 7: Battery Health Distribution
ax7 = fig.add_subplot(gs[3, 1])  # Bottom row, second column

# Get current health scores
current_health_scores = []
for battery in all_batteries:
    batt_data = df_features[df_features['battery_id'] == battery]
    if len(batt_data) > 0:
        current_health = batt_data['health_score'].iloc[-1]
        current_health_scores.append(current_health)

# Create histogram
n, bins, patches = ax7.hist(current_health_scores, bins=15, alpha=0.7,
                           color='steelblue', edgecolor='black')

# Color code the histogram bars
for i in range(len(patches)):
    if bins[i] < 70:
        patches[i].set_facecolor('red')
    elif bins[i] < 85:
        patches[i].set_facecolor('orange')
    else:
        patches[i].set_facecolor('green')

ax7.axvline(x=70, color='red', linestyle='--', linewidth=2, alpha=0.7, label='Critical (70%)')
ax7.axvline(x=85, color='orange', linestyle='--', linewidth=2, alpha=0.7, label='Warning (85%)')
ax7.set_xlabel('Health Score (%)', fontsize=11)
ax7.set_ylabel('Number of Batteries', fontsize=11)
ax7.set_title('Fleet Health Distribution', fontsize=13, fontweight='bold')
ax7.legend(loc='upper left', fontsize=9)
ax7.grid(True, alpha=0.3)

# PLOT 8: Correlation Matrix
ax8 = fig.add_subplot(gs[3, 2])  # Bottom row, third column

# Select features for correlation
corr_features = []
if 'health_score' in df_features.columns:
    corr_features.append('health_score')
if 'rul' in df_features.columns:
    corr_features.append('rul')
if 'soh' in df_features.columns:
    corr_features.append('soh')
if 'capacity' in df_features.columns:
    corr_features.append('capacity')
if 'cycle' in df_features.columns:
    corr_features.append('cycle')

if len(corr_features) >= 3:
    corr_matrix = df_features[corr_features].corr()
    im = ax8.imshow(corr_matrix, cmap='coolwarm', vmin=-1, vmax=1)

    # Add correlation values
    for i in range(len(corr_features)):
        for j in range(len(corr_features)):
            text_color = 'white' if abs(corr_matrix.iloc[i, j]) > 0.5 else 'black'
            ax8.text(j, i, f'{corr_matrix.iloc[i, j]:.2f}',
                    ha="center", va="center", color=text_color, fontsize=9, fontweight='bold')

    ax8.set_xticks(range(len(corr_features)))
    ax8.set_yticks(range(len(corr_features)))
    ax8.set_xticklabels([f[:8] for f in corr_features], rotation=45, ha='right', fontsize=9)
    ax8.set_yticklabels([f[:8] for f in corr_features], fontsize=9)

    ax8.set_title('Feature Correlation Matrix', fontsize=13, fontweight='bold')

    # Add colorbar
    plt.colorbar(im, ax=ax8, fraction=0.046, pad=0.04)
else:
    ax8.text(0.5, 0.5, 'Insufficient features\nfor correlation matrix',
            ha='center', va='center', transform=ax8.transAxes, fontsize=12)
    ax8.set_title('Feature Correlation', fontsize=13, fontweight='bold')

# PLOT 9: Battery Summary Statistics
ax9 = fig.add_subplot(gs[3, 3])  # Bottom row, fourth column

# Create summary table
summary_data = []
for battery in all_batteries:
    batt_data = df_features[df_features['battery_id'] == battery]
    if len(batt_data) > 0:
        latest = batt_data.iloc[-1]
        summary_data.append({
            'Battery': battery,
            'Cycles': int(latest['cycle']),
            'Health': f"{latest['health_score']:.1f}%",
            'RUL': f"{latest['rul']:.0f}",
            'Status': '🔴' if latest['health_score'] < 70 else
                     '🟡' if latest['health_score'] < 85 else
                     '🟢'
        })

# Hide axes for table
ax9.axis('tight')
ax9.axis('off')

if summary_data:
    # Create table
    summary_df = pd.DataFrame(summary_data)
    table = ax9.table(cellText=summary_df.values,
                     colLabels=summary_df.columns,
                     cellLoc='center',
                     loc='center',
                     colColours=['lightgray']*len(summary_df.columns))

    # Style the table
    table.auto_set_font_size(False)
    table.set_fontsize(10)
    table.scale(1, 2)

    # Color code health cells
    for i in range(1, len(summary_data) + 1):
        health_val = float(summary_data[i-1]['Health'].replace('%', ''))
        if health_val < 70:
            table[(i, 2)].set_facecolor('lightcoral')
        elif health_val < 85:
            table[(i, 2)].set_facecolor('lightyellow')
        else:
            table[(i, 2)].set_facecolor('lightgreen')

    ax9.set_title('Battery Summary', fontsize=13, fontweight='bold', pad=20)
else:
    ax9.text(0.5, 0.5, 'No summary data available',
            ha='center', va='center', transform=ax9.transAxes, fontsize=12)
    ax9.set_title('Battery Summary', fontsize=13, fontweight='bold')

plt.tight_layout()
plt.show()

print("✅ NASA MULTI-BATTERY Health Dashboard complete!")
print("\n" + "="*70)
print("DASHBOARD SUMMARY")
print("="*70)
print(f"📊 Dashboard Components:")
print(f"   1. Health Score Timeline - All {len(all_batteries)} batteries")
print(f"   2. RUL Projection - Predictive maintenance scheduling")
print(f"   3. Current Health Status - Color-coded battery status")
print(f"   4. Capacity Degradation - Performance comparison")
print(f"   5. Maintenance Timeline - Action planning")
print(f"   6. Degradation Rate - Failure risk assessment")
print(f"   7. Health Distribution - Fleet overview")
print(f"   8. Feature Correlation - Data insights")
print(f"   9. Battery Summary - Quick reference table")

print(f"\n🔋 Batteries Analyzed: {len(all_batteries)}")
for battery in all_batteries:
    batt_data = df_features[df_features['battery_id'] == battery]
    if len(batt_data) > 0:
        latest = batt_data.iloc[-1]
        status = "🔴 CRITICAL" if latest['health_score'] < 70 else \
                "🟡 WARNING" if latest['health_score'] < 85 else \
                "🟢 HEALTHY"
        print(f"   • {battery}: {status} (Health: {latest['health_score']:.1f}%, RUL: {latest['rul']:.0f} cycles)")

print(f"\n💡 Predictive Maintenance Insights:")
print("   • Real-time monitoring of entire battery fleet")
print("   • Early detection of degradation patterns")
print("   • Data-driven maintenance scheduling")
print("   • Fleet-wide health optimization")
print("   • ROI calculation for battery replacements")